<?php
/**
  * @file
  * Implementation of hook_nodequeue_add().
  *
  *https://drupal.stackexchange.com/questions/130668/write-a-file-locally
  *https://davidwalsh.name/basic-php-file-handling-create-open-read-write-append-close-delete
  *https://www.geeksforgeeks.org/php-date-time/
  *https://github.com/RobertoGarcia/nodequeue-log-drupal-7
  
  */
 function debug_nodequeue_nodequeue_add($sqid, $nid) {

     //$subqueue = subqueue_load($sqid);
     //nodequeue_queue_front($subqueue, $subqueue->count);

     $node = node_load($nid);
     dpm(" Nodequeue: " . $sqid . " nid: " . $nid );
     $file = 'public://nodequeue.log';
     //open file for writing ('w','r','a')
     $handle = fopen($file, 'a') or die('Cannot open file:  '.$file);
     //$handle = fopen($my_file, 'w') or die('Cannot open file:  '.$my_file);

     $timestamp = time();
     $data = "\n"."nodequeue|" . $sqid . "|nid|" . $nid ."|title|". trim($node->title) . "|timestamp|" . $timestamp . "|datetime|" . date("Y-m-d h:i:s", $timestamp);
     fwrite($handle, $data);
     fclose($handle);

}
